### PR TITLE
fix: typo in KVB regionalverkehr id

### LINKED ISSUE #34: KVB profile fails with journeys between two local stations
When integrating the work from #28 into my use case, I found that journeys between two local stations result in a `JourneysArrivalDepartureTooNearError` exception. As soon as one of the stations is a long-distance station, the journeys are retrieved, but seem to take a detour using a long-distance product.

With the DBProfile, this is not an issue.

I do not understand what is happening. But maybe it's more obvious to you. Here's a test script:

```py
import datetime

from pyhafas import HafasClient
from pyhafas.profile import KVBProfile

kvb = HafasClient(KVBProfile())

# This works: Two long-distance stations
departures   = kvb.locations('Köln Hbf')
destinations = kvb.locations('Bahnhof Deutz/Messe')

# This also works: Still one long-distance station
# But: The journey takes a detour through Köln Hbf, although there is a direct stadtbahn connection.
departures   = kvb.locations('Köln Heumarkt')

# This breaks: Two local stations only
# Result: pyhafas.types.exceptions.JourneysArrivalDepartureTooNearError: HAFAS Kernel: No connection found
destinations = kvb.locations('Deutzer Freiheit')

departure = departures[0]
destination = destinations[0]

print(departure)
print(destination)

journeys = kvb.journeys(
        origin=departure,
        destination=destination,
        date=datetime.datetime.now(),
        min_change_time=0,
        max_changes=-1
)

print(journeys)
```

@1Maxnet1, I'm tagging you as the author of  #28 . (Thanks again!) Maybe you have an idea?

### PR DESCRIPTION
**Pull request by akloeckner**
I dug a bit deeper and fixed a typo (reversed digits in the above ID) that seems to have fixed issue #34 .

fixes #34 

In case this gets merged, I would appreciate a minor release so I can proceed with my depending application. :-)

### CODE REVIEW

**Review by 1Maxnet1 — APPROVED** [review]
Good catch and thanks for fixing it. Looks good to me :)

**Comment by akloeckner** [comment]
Any chance for this fix to be merged and released soon?

**Review by leona-ya — APPROVED** [review]

**Comment by akloeckner** [comment]
Thanks for merging this, @leona-ya ! Could you also create a new release? I guess with #33 , it will be `0.5.0`?

**Comment by akloeckner** [comment]
Hey, I wanted to check back and ask again, if you could publish a new version to PyPI...

**Comment by 1Maxnet1** [comment]
> Hey, I wanted to check back and ask again, if you could publish a new version to PyPI...

Hey @akloeckner I already forwarded your request to the matrix room: https://matrix.to/#/#pyhafas:matrix.org but did not yet get an answer.

In the meantime you can either build a package of the current state on your own by running `python -m build` in the cloned repository or install it directly from git: `pip install git+https://github.com/FahrplanDatenGarten/pyhafas.git`

**Comment by leona-ya** [comment]
0.5.0 should now be published...

**Comment by akloeckner** [comment]
🎉 Thanks to both of you!

**Pull request merged**
